[package]
name = "cached"
version = "0.19.0"
authors = ["James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching"]
keywords = ["caching", "cache", "memoize", "lru"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "jaemk/cached", branch = "master" }

[features]
default = ["proc_macro"]
proc_macro = ["async-mutex", "cached_proc_macro"]
async = ["futures", "async-trait"]

[dependencies.once_cell]
version = "1"

[dependencies.async-mutex]
version = "1.1.5"
optional = true

[dependencies.cached_proc_macro]
version = "0.4.0"
path = "cached_proc_macro"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.async-trait]
version = "0.1"
optional = true

[dev-dependencies.tokio]
version = "0.2.21"
features = ["macros", "time"]

[dev-dependencies.async-std]
version = "1.6.2"
features = ["attributes"]

[workspace]
members = ["cached_proc_macro"]
